### ISSUE TITLE
Stutter in starting animation towards the end.(Low priority)

### ISSUE THREAD

**Issue by JonathanLochridge** [lassefolkersen/highfrontier#14]
I found a stutter in the starting animation that occurs in the new PR, but I don't think occurs, or at least isn't noticable before it.

Not super important, and I would take a stutter if we have something bigger fixed.

**Comment by lassefolkersen** [comment]
Oh, just saw this. Perfect. It's super easy to revert. Just delete *30 [here](https://github.com/lassefolkersen/highfrontier/blob/d7d864fa87be1a49dd5da62314c3ab0c3f819002/intro.py#L60) and [here](https://github.com/lassefolkersen/highfrontier/blob/d7d864fa87be1a49dd5da62314c3ab0c3f819002/intro.py#L202). (and btw I think maybe [here](https://github.com/lassefolkersen/highfrontier/blob/master/global_variables.py#L34), would have been the right place to edit. I just forgot 😄 )

I'll go ahead and do it, but maybe let's just check a little more - because the reason I put it in was that intro sequence looked much too fast on my laptop now. It's supposed to zoom in from viewing all the solar system to just a slowly spinning earth.
